print("My name is Jahnavi")
print("My father name is Sreeram") 
print("My mother name is Uma")
print("My hobbies are watching movies and dancing")
print("My intrests are knowing new things")
print("I am studying Bsc data science 2nd year")
print("My favorite color is black")
